name: Lint and tests
on:
  push:
    branch: [ '*' ]
  pull_request:
    branch: [ '*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js setup
      uses: actions/setup-node@v1
    - name: Installation of dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Unit tests
      run: npm run test:unit
    - name: E2E tests
      run: npm run test:e2e
